PRODUCT_PLATFORM := MSM8226

# Copyright (C) 2012 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_PACKAGES += \
3a_info_parser \
a225_pfp \
a225_pm4 \
a225p5_pm4 \
a300_pfp \
a300_pm4 \
a330_pfp \
a330_pm4 \
adaptive \
addict \
adsprpc \
adsprpcd \
alIAF_InData_4M2M \
ansi_cprng \
ATFWD-daemon \
audio.a2dp.default \
audio.mirrorlink.default \
audio.primary.default \
audio.primary.msm8226 \
audio.r_submix.default \
audio.usb.default \
awb_camera \
blkid \
bluetooth.default \
bma150_usr \
brcmapd \
brctl \
bridgemgrd \
btnvtool \
camera.msm8226 \
camera_test \
cand \
ccibdt \
charger_monitor \
charging \
chiaddict \
clatd \
climax \
clockd \
cmnlib \
cmnlib_b00 \
cmnlib_b01 \
cmnlib_b02 \
cmnlib_b03 \
cnd \
copybit.msm8226 \
cpp_firmware_v1_1_1 \
cpp_firmware_v1_1_6 \
cpp_firmware_v1_2_0 \
crda \
curl \
diag_callback_client \
diag_dci_sample \
diag_klog \
diag_mdlog \
diag_socket_log \
diag_uart_log \
dma_test \
dmagent \
dm-crypt \
dnsmasq \
ds_fmc_appd \
dsdnsutil \
dual_camera \
dxhdcp2_b00 \
dxhdcp2_b01 \
dxhdcp2_b02 \
dxhdcp2_b03 \
dxhdcp2_mdt \
e2fsck \
ebtables \
ecryptfs \
evbug \
exfatck \
exfatdebug \
exfatinfo \
exfatlabel \
flash_camera \
flash_spcustom \
flatland \
fm_drc \
fm_eq \
fm_l_drc \
fm_l_eq \
fm_l_preset \
fm_preset \
ftm_proc_daemon \
ftmdaemon \
fusermount \
gps.default \
gralloc.msm8226 \
gspca_main \
hcheck \
hcheck_b00 \
hcheck_b01 \
hcheck_b02 \
hcheck_b03 \
hcheck_mdt \
hci_qcomm_init \
hostapd \
hostapd_cli \
htc_ebdlogd \
htcbarocal_csd \
htccrypto_b00 \
htccrypto_b01 \
htccrypto_b02 \
htccrypto_b03 \
htccrypto_mdt \
hvdcp \
hwcomposer.msm8226 \
ILP0100_IPM_Code_out \
ILP0100_IPM_Data_out \
ip \
ipv6tether \
irsc_util \
iw \
iwlist \
iwpriv \
keypress \
keystore.msm8226 \
l2_profile_exchange \
leia_pfp_470 \
leia_pm4_470 \
libacc \
libaddrsdetection \
libalDE \
libalDE_SDE_TWO \
libalDynamicWarping_SDW_TWO \
liballjoyn \
libandroid_simlock \
libAppDataSearch \
libaricentomxplugin \
libaudioparameter \
libaudio-resampler \
libaudioroute \
libAudioTrimmer \
libAutoK \
libawb_calibration \
libbdpush_V1_0 \
libBeautyChat \
libbluedroid \
libbluetooth_jni \
libbson \
libbt-aptx-4.0.3 \
libbt-hci \
libbt-utils \
libbv_panodata \
libbv_panodata_hdk_v4 \
libc2dcolorconvert \
libcamera_aec \
libcamera_af \
libcamera_awb \
libcameraface \
libcamerapp \
libcciftm \
libcfiril \
libChange \
libchecksum \
libchrome.1985.135 \
libcimagegif-jni \
libclcore_neon \
libcld \
libcnefeatureconfig \
libcnelog \
libconscrypt_gmscore_jni \
libcootek_pte_oem \
libcpt9 \
libcpt9core \
libcpt9provider \
libcrashreporter \
libcronet \
libcryptox \
libcurl \
libdapcert \
libdaptpm \
libdivxdrmdecrypt \
libdm \
libDMCmd \
libdocscanner_image \
libdocsimageutils \
libDotView \
libdrmdecrypt \
libdumppcm \
libebt_802_3 \
libebt_among \
libebt_arp \
libebt_arpreply \
libebt_ip \
libebt_ip6 \
libebt_limit \
libebt_log \
libebt_mark \
libebt_mark_m \
libebt_nat \
libebt_nflog \
libebt_pkttype \
libebt_redirect \
libebt_standard \
libebt_stp \
libebt_ulog \
libebt_vlan \
libebtable_broute \
libebtable_filter \
libebtable_nat \
libebtc \
libemoji \
libEX_Engine5 \
libexif_lib1_jni_v07 \
libexif_lib1_v07 \
libext2_blkid \
libext2_com_err \
libext2_e2p \
libext2_profile \
libext2_uuid \
libext2fs \
libext3-fileio \
libexternal \
libfacelock_jni \
libfb \
libfb_breakpad_client \
libfb_cpucapabilities \
libfb_crypto \
libfb_dalvik-internals \
libfb_filesystem \
libfb_imgproc \
libfb_jpegturbo \
libfb_stl_shared \
libfb_tracker \
libfbjni \
libfilterframework_jni \
libfilterpack_facedetect \
libframesequence \
libfrsdk \
libfuse \
libgames_rtmp_jni \
libgcastv2_base \
libgcastv2_support \
libgdvoucher \
libgdvoucher_jni \
libgifdecoder \
libgifdecoder2 \
libgmm-jni \
libgmscore \
libgnencryption.3.3.3.15 \
libgnlocal_lookup.3.3.3.15 \
libgnmc_aactag.3.3.3.15 \
libgnmc_decoder.3.3.3.15 \
libgnmc_fpx.3.3.3.15 \
libgnmc_id3tag.3.3.3.15 \
libgntransition_detector.3.3.3.15 \
libgnustl_shared \
libgoogle_hotword_jni \
libgoogle_recognizer_jni_l \
libgps.utils \
libharfbuzz \
libHMSGallery_almashot-clr \
libHMSGallery_almashot-seamless \
libHMSGallery_beat \
libHMSGallery_bvjni \
libHMSGallery_enhancer_vheffects \
libHMSGallery_eOkao \
libHMSGallery_facedetector \
libHMSGallery_feature_extractor \
libHMSGallery_libAnalyst \
libHMSGallery_libAutoKJni \
libHMSGallery_libBokehLibEngine \
libHMSGallery_libCutAndPaste \
libHMSGallery_libcutils_plus \
libHMSGallery_libDepthmapJni \
libHMSGallery_libDualLens \
libHMSGallery_libDualLensEngine \
libHMSGallery_libDuoShare \
libHMSGallery_libglcv \
libHMSGallery_libImageAlignment \
libHMSGallery_libMatrix \
libHMSGallery_libNEONImage \
libHMSGallery_libNewTimeBreakin \
libHMSGallery_libSegBokeh \
libHMSGallery_libThumbnailUtility \
libHMSGallery_MediaNaive \
libHMSGallery_sunny \
libHMSGallery_svm \
libHMSGallery_swapheap \
libHMSGallery_vheffects \
libHMSGallery_yuvimage \
libhostapd_client \
libhtc_framework \
libhtc_loglevel \
libhtc_rilhook \
libhtccamera \
libhtcdm \
libhtcdrm1 \
libhtcflag_native \
libhtcflag-jni \
libhtcflash \
libhtcime_baseinputmethod_jni \
libhtcime_baseinputmethod2_jni \
libhtcmfg \
libhtcomaplugin \
libhtcqxdm2sd \
libhtcsecure \
libicule \
libiculx \
libimagelib \
libiprouteutil \
libjDTCPDaemon \
libjgcastservice \
libjHTCMediaServerManager \
libjni_fe \
libjni_gifCreator \
libjpush \
libjSebring \
libjUPnPCP \
libkikin \
libkineto \
liblmirescue_v18 \
libloc_api_v02 \
libloc_core \
libloc_ds_api \
libloc_eng \
liblz \
libmemalloc \
libmmcamera_interface \
libmmjpeg_interface \
libmm-omxcore \
libmm-qcamera \
libmode10 \
libmode10AutoTest \
libmode10fx \
libmode10GLES20 \
libmorpho_edit_engine \
libmorpho_frame_overlay \
libmorpho_image_converter \
libmorpho_image_stitcher3 \
libmorpho_image_transform \
libmorpho_jpeg_io \
libmorpho_memory_allocator \
libmoviemaker-jni \
libmss \
libmss.so \
libMusicVisualizer \
libmvpnc \
libnetjni \
libnetlink \
libnetsharing \
libnl \
libnl_2 \
libocrclient \
libOlaEngineNew \
libOmxAacEnc \
libOmxAmrEnc \
libOmxCore \
libOmxEvrcEnc \
libOmxQcelp13Enc \
libOmxVdec \
libOmxVdecHevc \
libOmxVenc \
libopencv_java \
libopencv_porting \
liboverlay \
libpanoglviewer \
libpanoglviewer_hdk_v13 \
libpanoramaplus \
libpanostitcher \
libpatts_engine_jni_api_ub.210030103 \
libpeanut \
libphotoeditor_native \
libpluginoptimizer \
libpolarisoffice5 \
libpolarisofficeSDK \
libposteffect \
libpphwr \
libpphwrcore \
libpphwrphrase \
libprojector \
libqcomomxsample_jb \
libqcompostprocbundle \
libqdMetaData \
libqdutils \
libqomx_core \
libqsap_sdk \
libqservice \
libQWiFiSoftApCfg \
librectifier \
libreflex \
libreflex-jni \
librilswitch \
librsjni \
libRSSupport \
libsmith \
libspeexwrapper \
libsrsprocessing \
libstagefright_hdcp \
libstagefright_soft_aacdec1 \
libstagefrighthw \
libstopmotion \
libSwypeCore \
libt9 \
libtinycompress \
libtinyxml \
libtuning_aec \
libtuning_aec_s5k5e2_twolane_hdr \
libtuning_aec_s5k5e2_twolane_hdr_16_9 \
libtuning_aec_s5k5e2_twolane_video \
libtuning_aec_s5k5e2_twolane_video_16_9 \
libtuning_aec_s5k5e2_twolane_video_60fps \
libtuning_aec_s5k5e2_twolane_videoHFR \
libtuning_aec_s5k5e2_twolane_zsl \
libtuning_aec_s5k5e2_twolane_zsl_16_9 \
libtuning_aec_s5k6a1gx_hdr \
libtuning_aec_s5k6a1gx_video \
libtuning_aec_s5k6a1gx_zsl \
libtuning_af \
libtuning_awb_s5k5e2_twolane \
libtuning_awb_s5k6a1gx \
libusbnetjni \
libvcdecoder_jni \
libvdmengine \
libvdmfumo \
libvelodsf \
libvelodsf.sign \
libvideochat_jni \
libvideoeditor_core \
libvideoeditor_jni \
libvideoeditor_osal \
libvideoeditor_videofilters \
libvideoeditorplayer \
libvirtual \
libwebcore \
libwebp \
libwebp_android \
libwebrtc_audio_coding \
libwivu \
libwsp \
libwsp_jni \
libWVphoneAPI \
libxml2 \
libyuv2rgb_neon \
lights.msm8226 \
linville.key.pub \
logcat2 \
logparser_linux \
lsc_camera \
lscbuffer_rev2 \
mcdrvmodule \
mckernelapi \
mcStarter \
memtrack.msm8226 \
mirlink_b00 \
mirlink_b01 \
mirlink_b02 \
mirlink_b03 \
mirlink_mdt \
mke2fs \
mkexfat \
mmc_test \
mm-jpeg-dec-test \
mm-jpeg-enc-test \
mm-qcamera-app \
mm-qcamera-daemon \
mm-qjpeg-dec-test \
mm-qjpeg-enc-test \
mm-qomx-idec-test \
mm-qomx-ienc-test \
mm-vdec-omx-test \
mm-venc-omx-test720p \
mm-video-driver-test \
mm-video-encdrv-test \
moc_crypto.ko.3.4 \
moc_crypto.ko.sig.3.4 \
MOC_ecryptfs_add_passphrase \
moc_platform_mod.ko.3.4 \
MOC_umount_ecryptfs \
mpdecision \
msm-buspm-dev \
n_smux \
netmgrd \
netsharing \
nl_listener \
parseJpeg_dev \
PktRspTest \
playback \
playback_eq \
playback_l_drc \
playback_l_eq \
playback_l_preset \
playback_preset \
playbackMFG_config \
playbackMFG_drc \
playbackMFG_eq \
playbackMFG_l_config \
playbackMFG_l_drc \
playbackMFG_l_eq \
playbackMFG_l_preset \
playbackMFG_preset \
playbackwoofer_drc \
playbackwoofer_eq \
playbackwoofer_l_drc \
playbackwoofer_l_eq \
playbackwoofer_l_preset \
playbackwoofer_preset \
pnpmgr \
port-bridge \
power.default \
pronto_wlan \
ptt_socket_app \
qb_offmode_alarm \
qcedev \
qcrypto \
qmiproxy \
qmuxd \
qrngd \
qrngtest \
qseecomd \
radio-iris-transport \
radish \
radvd \
readDapCert \
Rec_Video_drc \
Rec_Video_eq \
Rec_Video_l_drc \
Rec_Video_l_eq \
Rec_Video_l_preset \
Rec_Video_preset \
regdbdump \
regulatory \
reset_modem \
rmt_storage \
scsi_wait_scan \
sensors \
sensors.msm8226 \
setup_fs \
shutdown \
spidev \
tc \
test_diag \
testclient \
testserver \
texfat \
tfa9895_config \
tfa9895_l_speaker \
tfa9895_patch \
tfa9895_speaker \
tfa9895MFG_patch \
thermal-engine \
time_daemon \
tinycap \
tinymix \
tinypcminfo \
tinyplay \
touchevent \
touchscreen \
tune2fs \
udhcpd \
usbhub \
usbhub_init \
venus_b00 \
venus_b01 \
venus_b02 \
venus_b03 \
venus_b04 \
venus_mbn \
venus_mdt \
voice_drc \
voice_eq \
voice_l_drc \
voice_l_eq \
voice_l_preset \
voice_preset \
voiceWB_eq \
voiceWB_l_eq \
voip_drc \
voip_eq \
voip_l_drc \
voip_l_eq \
voip_l_preset \
voip_preset \
WCNSS_cfg \
WCNSS_qcom_cfg \
WCNSS_qcom_wlan_nv \
wcnss_service \
widevine \
widevine_b00 \
widevine_b01 \
widevine_b02 \
widevine_b03 \
wpa_supplicant \
zchgd

